//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdealSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionarios
    {
        public int Id_Func { get; set; }
        public string Nome { get; set; }
        public string Sobrenome { get; set; }
        public string telefone { get; set; }
    }
}
